-- Objects that are hard to introspect and to rebuild as DDL.
DROP SCHEMA IF EXISTS herdr_fixture CASCADE;
CREATE SCHEMA herdr_fixture;
SET search_path = herdr_fixture;

CREATE TYPE mood AS ENUM ('happy', 'sad');

CREATE FUNCTION touch() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.created_at := now();
    RETURN NEW;
END
$$;

CREATE TABLE orgs (
    id serial PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE orgs IS 'Organisations clientes';
COMMENT ON COLUMN orgs.name IS 'Nom affiché, l''unique';
CREATE TRIGGER orgs_touch BEFORE UPDATE ON orgs FOR EACH ROW EXECUTE FUNCTION touch();

CREATE TABLE memberships (
    org_id integer NOT NULL REFERENCES orgs (id) ON DELETE CASCADE,
    user_id bigint NOT NULL,
    role text NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin')),
    PRIMARY KEY (org_id, user_id)
);

CREATE TABLE "Audit Log" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id integer NOT NULL,
    user_id bigint NOT NULL,
    "Event Type" mood NOT NULL,
    payload jsonb,
    price numeric(10, 2) NOT NULL DEFAULT 0,
    qty integer NOT NULL DEFAULT 1,
    total numeric GENERATED ALWAYS AS (price * qty) STORED,
    note text,
    CONSTRAINT audit_membership_fk FOREIGN KEY (org_id, user_id) REFERENCES memberships (org_id, user_id)
);
COMMENT ON TABLE "Audit Log" IS 'Journal d''audit';
CREATE INDEX audit_payload_idx ON "Audit Log" USING gin (payload);
CREATE INDEX audit_lower_note_idx ON "Audit Log" (lower(note)) WHERE note IS NOT NULL;

CREATE TABLE events (
    id bigint NOT NULL,
    happened_at date NOT NULL,
    label text,
    PRIMARY KEY (id, happened_at)
) PARTITION BY RANGE (happened_at);
CREATE TABLE events_2025 PARTITION OF events FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
CREATE TABLE events_2026 PARTITION OF events FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

CREATE TABLE big (
    id integer PRIMARY KEY,
    label text NOT NULL,
    maybe text
);
INSERT INTO big
SELECT g, 'row ' || lpad(g::text, 6, '0'),
       CASE g % 3 WHEN 0 THEN NULL WHEN 1 THEN '' ELSE 'x' END
FROM generate_series(1, 300000) AS g;

CREATE VIEW org_members AS
SELECT o.name, m.user_id FROM orgs o JOIN memberships m ON m.org_id = o.id;

CREATE MATERIALIZED VIEW org_counts AS
SELECT org_id, count(*) AS n FROM memberships GROUP BY org_id;
CREATE UNIQUE INDEX org_counts_idx ON org_counts (org_id);

INSERT INTO orgs (name) VALUES ('Hellocare'), ('Acme');
INSERT INTO memberships VALUES (1, 10, 'admin'), (1, 11, 'member'), (2, 20, 'member');
INSERT INTO events VALUES (1, '2025-03-01', 'a'), (2, '2026-03-01', 'b');
INSERT INTO "Audit Log" (org_id, user_id, "Event Type", payload, price, qty, note)
VALUES (1, 10, 'happy', '{"k": [1, 2]}', 9.5, 2, NULL), (1, 11, 'sad', NULL, 0, 1, '');
REFRESH MATERIALIZED VIEW org_counts;
ANALYZE;
